# -*- coding: utf-8 -*-
"""Probability-Density-Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYHlrxFhF0DOCEes8zvbZOOTWmBDAVE-
"""

import pandas as pd
import numpy as np
from scipy.optimize import curve_fit

FILE_PATH = 'data.csv'
ROLL_NUMBER = 102317090

df = pd.read_csv(FILE_PATH, encoding='latin1')
x_data = df['no2'].dropna().values

ar = 0.05 * (ROLL_NUMBER % 7)
br = 0.3 * ((ROLL_NUMBER % 5) + 1)

print(f"Calculated Constants: ar = {ar}, br = {br}")

z_data = x_data + ar * np.sin(br * x_data)

def target_pdf(z, c, lam, mu):
    return c * np.exp(-lam * (z - mu)**2)

hist_values, bin_edges = np.histogram(z_data, bins='auto', density=True)
bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

initial_guesses = [max(hist_values), 1/(2*np.var(z_data)), np.mean(z_data)]

popt, pcov = curve_fit(target_pdf, bin_centers, hist_values, p0=initial_guesses)

c_opt, lambda_opt, mu_opt = popt

print("-" * 30)
print("FINAL PARAMETERS TO SUBMIT:")
print(f"Lambda (λ): {lambda_opt}")
print(f"Mu (μ):     {mu_opt}")
print(f"c:          {c_opt}")
print("-" * 30)